name: Update README Workflow

on:
  push:
    branches:
      - main  # Adjust this to the main branch name


jobs:
  update_readme:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        # with:
        #   token: ${{ secrets.GITHUB_TOKEN }}


      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      - name: Run Python Script
        run: |
          cd ${{ github.workspace }} && ls -la
          python_path="$(which python)"
          output=$(${python_path} ${{ github.workspace }}/mix.py -pr .github/workflows/README.md -py .github/workflows)
          echo "$output"  # Print captured output to the console
          git config --global user.email "milos.miljanovic@htecgroup.com"
          git config --global user.name "Milos Miljanovic"
          git add .
          git commit -m "Change"
          git push

      - name: Capture Output as Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: script-output
          path: test/output/
